"""
This script gives us reproducible builds of the fonts themselves, so that we don't recreate the font unnecessarily.

"""
import datetime
import os
import shutil
import time

import fontforge


base = '../font/'
sfd = os.path.join(base, 'xkcd-script.sfd')
newsfd = os.path.join(base, 'new-xkcd-script.sfd')
ttf = os.path.join(base, 'xkcd-script.ttf')
woff = os.path.join(base, 'xkcd-script.woff')

if True:
    content = []
    with open(sfd, 'rb') as fh_in:
        for line in fh_in:
            try:
                line = line.decode('utf-8')
            except UnicodeDecodeError:
                content.append(line)
                continue

            if line.startswith('%%CreationDate'):
                line = '%%CreationDate: Sat Jan 1 00:00:00 2000\n'

            if 'Created with FontForge (http://fontforge.org)' in line:
                line = '% Created with FontForge (http://fontforge.org)\n'

            if 'Generated by FontForge' in line:
                continue

            content.append(line.encode('utf-8'))

    with open(newsfd, 'wb') as fh_out:
        for line in content:
            fh_out.write(line)

os.remove(sfd)
shutil.move(newsfd, sfd)

then = datetime.datetime(2000, 1, 1, 0, 0)
then = time.mktime(then.timetuple())
os.utime(sfd, (then, then))

font = fontforge.open(sfd)
font.generate(woff)
font.generate(ttf)
