"""
This script gives us reproducible builds of the fonts themselves, so that we don't recreate the font unnecessarily.

"""
import datetime
import os
import shutil
import calendar

import fontforge


base = '../font/'
sfd = os.path.join(base, 'xkcd-script.sfd')
newsfd = os.path.join(base, 'new-xkcd-script.sfd')
otf = os.path.join(base, 'xkcd-script.otf')
ttf = os.path.join(base, 'xkcd-script.ttf')
woff = os.path.join(base, 'xkcd-script.woff')

if True:
    content = []
    with open(sfd, 'rb') as fh_in:
        for line in fh_in:
            try:
                line = line.decode('utf-8')
            except UnicodeDecodeError:
                content.append(line)
                continue

            if line.startswith('%%CreationDate'):
                line = '%%CreationDate: Sat Jan 1 00:00:00 2000\n'

            if line.startswith('CreationTime:'):
                line = 'CreationTime: 946684800\n'

            if line.startswith('ModificationTime:'):
                line = 'ModificationTime: 946684800\n'

            if 'Created with FontForge (http://fontforge.org)' in line:
                if line.startswith('UComments:'):
                    line = 'UComments: "Created with FontForge (http://fontforge.org)"\n'
                else:
                    line = '% Created with FontForge (http://fontforge.org)\n'

            if 'Generated by FontForge' in line:
                continue

            content.append(line.encode('utf-8'))

    with open(newsfd, 'wb') as fh_out:
        for line in content:
            fh_out.write(line)

os.remove(sfd)
shutil.move(newsfd, sfd)

then = datetime.datetime(2000, 1, 1, 0, 0)
then = calendar.timegm(then.timetuple())
os.utime(sfd, (then, then))

font = fontforge.open(sfd)

# Pin the UniqueID so FontForge doesn't embed a build date (breaks reproducibility).
font.sfnt_names = (('English (US)', 'UniqueID', 'xkcd Script'), )
font.xuid = "-1"

# Pin line metrics: generate() recomputes hhea/win from glyph bounding boxes unless _add=False.
font.os2_typoascent      = font.ascent;  font.os2_typoascent_add  = False
font.os2_typodescent     = -font.descent; font.os2_typodescent_add = False
font.os2_typolinegap     = 77
font.os2_winascent       = 855;  font.os2_winascent_add   = False
font.os2_windescent      = 270;  font.os2_windescent_add  = False
font.hhea_ascent         = 855;  font.hhea_ascent_add     = False
font.hhea_descent        = -270; font.hhea_descent_add    = False
font.hhea_linegap        = 77

font.generate(otf)
font.generate(ttf)
font.generate(woff)
