"""
Produce reproducible binary fonts (OTF / TTF / WOFF) for xkcd-script from
the pt7 SFD.

NOTE: this step runs *after* pt8_derivatives.py (which now also lives in
the pt8 slot).  Keeping the original pt8_ name here intentionally to
minimise diff noise during the MathJax PR; a follow-up should renumber
this to pt9_ and reserve pt8_ for the derivatives orchestrator.

  1. Scrub timestamps + XUID from the input SFD so FontForge can't bake
     build-time metadata into the output.
  2. Save the scrubbed SFD as the canonical committed copy.
  3. Open with FontForge, pin sfnt UniqueID + XUID, generate OTF/TTF/WOFF.
  4. (OTF) inline the committed reference OTF's charstrings byte-for-byte
     for any glyph whose outline is unchanged — keeps subpixel hint
     rendering stable across rebuilds even when other glyphs are added.
"""
import datetime
import os
import calendar
from pathlib import Path

import fontforge
from fontTools.ttLib import TTFont as _TTFont
from fontTools.pens.recordingPen import RecordingPen as _RecordingPen


GENERATED = '../generated/'
FONT_DIR  = '../font/'

_then_str  = 'Sat Jan 1 00:00:00 2000'
_then_unix = calendar.timegm(datetime.datetime(2000, 1, 1, 0, 0).timetuple())


NAME    = 'xkcd-script'
SFD_IN  = GENERATED + 'xkcd-script-pt7.sfd'
SFD_OUT = FONT_DIR  + 'xkcd-script.sfd'   # canonical, committed


# ---------------------------------------------------------------------------
# SFD scrubbing — strip build-time metadata so FontForge produces stable bytes
# ---------------------------------------------------------------------------

def scrub_sfd(sfd_in, sfd_out):
    content = []
    with open(sfd_in, 'rb') as fh_in:
        for line in fh_in:
            try:
                line = line.decode('utf-8')
            except UnicodeDecodeError:
                content.append(line)
                continue

            if line.startswith('%%CreationDate'):
                line = '%%CreationDate: ' + _then_str + '\n'
            if line.startswith('CreationTime:'):
                line = 'CreationTime: ' + str(_then_unix) + '\n'
            if line.startswith('ModificationTime:'):
                line = 'ModificationTime: ' + str(_then_unix) + '\n'
            if line.startswith('XUID:'):
                line = 'XUID: [-1]\n'
            if 'Created with FontForge (http://fontforge.org)' in line:
                if line.startswith('UComments:'):
                    line = 'UComments: "Created with FontForge (http://fontforge.org)"\n'
                else:
                    line = '% Created with FontForge (http://fontforge.org)\n'
            if 'Generated by FontForge' in line:
                continue

            content.append(line.encode('utf-8'))

    Path(os.path.dirname(sfd_out)).mkdir(exist_ok=True)
    with open(sfd_out, 'wb') as fh_out:
        for line in content:
            fh_out.write(line)
    os.utime(sfd_out, (_then_unix, _then_unix))


# ---------------------------------------------------------------------------
# CFF charstring freezing — preserve hint rendering for unchanged glyphs
# ---------------------------------------------------------------------------
# FontForge re-hints every glyph at generate() time; adding new glyphs to the
# font perturbs the hint program for *existing* glyphs, which shifts their
# subpixel rasterisation.  We freeze each unchanged glyph by overwriting its
# fresh charstring with the byte-identical program from the previously
# committed OTF (subr calls inlined so subr-index differences don't matter).

def _subr_bias(n):
    return 107 if n < 1240 else (1131 if n < 33900 else 32768)


def _inline_subrs(program, subrs, bias):
    out = []
    for token in program:
        if token == 'callsubr':
            idx = out.pop() + bias
            sub = subrs[idx]
            sub.decompile()
            inlined = _inline_subrs(sub.program, subrs, bias)
            if inlined and inlined[-1] == 'return':
                inlined = inlined[:-1]
            out.extend(inlined)
        else:
            out.append(token)
    return out


def freeze_cff(otf_path, name, ref_otf):
    """Inline ref_otf's charstrings into otf_path for any unchanged glyph,
    then desubroutinize all remaining charstrings (so the next run's reference
    is already inlined and the saved bytes match exactly)."""
    _ref_top = ref_otf['CFF '].cff.topDictIndex[0]
    _ref_cs  = _ref_top.CharStrings
    _ref_subrs = _ref_top.Private.Subrs
    _ref_bias  = _subr_bias(len(_ref_subrs))

    _new_otf = _TTFont(otf_path, recalcTimestamp=False)
    _new_otf.sfnt_names = (('English (US)', 'UniqueID', name), )
    _new_otf.xuid = "-1"

    _new_cs = _new_otf['CFF '].cff.topDictIndex[0].CharStrings
    _ref_glyphs = ref_otf.getGlyphSet()
    _new_glyphs = _new_otf.getGlyphSet()

    for _name in _ref_cs.keys():
        if _name not in _new_cs:
            continue
        # Only freeze glyphs whose outlines are unchanged.  If the path differs
        # the glyph was intentionally modified and FontForge's new hints should
        # be kept.
        _rp_ref = _RecordingPen(); _ref_glyphs[_name].draw(_rp_ref)
        _rp_new = _RecordingPen(); _new_glyphs[_name].draw(_rp_new)
        if _rp_ref.value != _rp_new.value:
            continue
        _cs = _ref_cs[_name]
        _cs.decompile()
        _inlined = _inline_subrs(_cs.program, _ref_subrs, _ref_bias)
        _new_cs[_name].program  = _inlined
        _new_cs[_name].bytecode = None

    # Desubroutinize every remaining charstring so subsequent runs' references
    # are already inlined → byte-identical re-encoding.
    _new_top = _new_otf['CFF '].cff.topDictIndex[0]
    _new_subrs = getattr(_new_top.Private, 'Subrs', [])
    _new_bias = _subr_bias(len(_new_subrs))
    for _name in _new_cs.keys():
        _cs = _new_cs[_name]
        if _cs.bytecode is not None:
            _cs.decompile()
        if _cs.program is None:
            continue
        _cs.program = _inline_subrs(_cs.program, _new_subrs, _new_bias)
        _cs.bytecode = None

    _new_otf.save(otf_path)


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

Path(FONT_DIR).mkdir(exist_ok=True)

print(f"=== {NAME} ===")

scrub_sfd(SFD_IN, SFD_OUT)

font = fontforge.open(SFD_OUT)
font.sfnt_names = (('English (US)', 'UniqueID', NAME),)
font.xuid = "-1"

out_base  = FONT_DIR + NAME
otf_path  = out_base + '.otf'
ttf_path  = out_base + '.ttf'
woff_path = out_base + '.woff'

# Snapshot the existing OTF (if any) before overwriting, for CFF freezing.
ref_otf = _TTFont(otf_path) if os.path.exists(otf_path) else None

font.generate(otf_path, flags=('opentype',))
print(f"  generated {otf_path}")

font.generate(ttf_path)
print(f"  generated {ttf_path}")

# FontForge produces WOFF directly so the CFF stays subroutinized.
# Wrapping the desubroutinized post-freeze OTF instead would inflate
# the woff by ~40% with no functional gain.
font.generate(woff_path)
print(f"  generated {woff_path}")

font.close()

if ref_otf is not None:
    freeze_cff(otf_path, NAME, ref_otf)
    print(f"  froze CFF for {otf_path}")
