"""
Produce reproducible binary fonts (OTF / TTF / WOFF) from the SFDs left in
generated/ by earlier pipeline steps.

Each variant in VARIANTS is processed independently:
  1. Scrub timestamps + XUID from the input SFD so FontForge can't bake
     build-time metadata into the output.
  2. Save the scrubbed SFD (canonical for the main font; intermediate for
     derivative variants).
  3. Open with FontForge, pin sfnt UniqueID + XUID, generate the requested
     output formats.
  4. (OTF only, when freeze_cff is set) inline the committed reference
     OTF's charstrings byte-for-byte for any glyph whose outline is
     unchanged — keeps subpixel hint rendering stable across rebuilds
     even when other glyphs are added.

To add a new derivative font: append a new entry to VARIANTS pointing at
the SFD that pt8_derivative_fonts.py wrote.
"""
import datetime
import os
import calendar
from pathlib import Path

import fontforge
from fontTools.ttLib import TTFont as _TTFont
from fontTools.pens.recordingPen import RecordingPen as _RecordingPen
from fontTools.subset import Subsetter as _Subsetter


GENERATED = '../generated/'
FONT_DIR  = '../font/'

_then_str  = 'Sat Jan 1 00:00:00 2000'
_then_unix = calendar.timegm(datetime.datetime(2000, 1, 1, 0, 0).timetuple())


VARIANTS = [
    {
        'name': 'xkcd-script',
        'sfd_in':   GENERATED + 'xkcd-script-pt7.sfd',
        'sfd_out':  FONT_DIR  + 'xkcd-script.sfd',          # canonical, committed
        'formats':  ['otf', 'ttf', 'woff'],
        'freeze_cff':       True,
        # Full font: FontForge generates WOFF directly so the CFF stays
        # subroutinized and the woff stays small.
        'subset_unicodes':  None,
    },
    {
        'name': 'xkcd-script-mathjax',
        'sfd_in':   GENERATED + 'xkcd-script-mathjax-pt8.sfd',
        'sfd_out':  GENERATED + 'xkcd-script-mathjax.sfd',  # intermediate, not committed
        'formats':  ['woff'],
        'freeze_cff':       False,
        # Delta font: WOFF wraps a fontforge-generated intermediate OTF then
        # subsets to just the codepoints this derivative actually overrides.
        # Everything else MathJax needs falls through to xkcd-script via the
        # font-face stack in xkcd-mathjax.js.
        'subset_unicodes':  [0x2211, 0x220F, 0x222B],
    },
]


# ---------------------------------------------------------------------------
# SFD scrubbing — strip build-time metadata so FontForge produces stable bytes
# ---------------------------------------------------------------------------

def scrub_sfd(sfd_in, sfd_out):
    content = []
    with open(sfd_in, 'rb') as fh_in:
        for line in fh_in:
            try:
                line = line.decode('utf-8')
            except UnicodeDecodeError:
                content.append(line)
                continue

            if line.startswith('%%CreationDate'):
                line = '%%CreationDate: ' + _then_str + '\n'
            if line.startswith('CreationTime:'):
                line = 'CreationTime: ' + str(_then_unix) + '\n'
            if line.startswith('ModificationTime:'):
                line = 'ModificationTime: ' + str(_then_unix) + '\n'
            if line.startswith('XUID:'):
                line = 'XUID: [-1]\n'
            if 'Created with FontForge (http://fontforge.org)' in line:
                if line.startswith('UComments:'):
                    line = 'UComments: "Created with FontForge (http://fontforge.org)"\n'
                else:
                    line = '% Created with FontForge (http://fontforge.org)\n'
            if 'Generated by FontForge' in line:
                continue

            content.append(line.encode('utf-8'))

    Path(os.path.dirname(sfd_out)).mkdir(exist_ok=True)
    with open(sfd_out, 'wb') as fh_out:
        for line in content:
            fh_out.write(line)
    os.utime(sfd_out, (_then_unix, _then_unix))


# ---------------------------------------------------------------------------
# CFF charstring freezing — preserve hint rendering for unchanged glyphs
# ---------------------------------------------------------------------------
# FontForge re-hints every glyph at generate() time; adding new glyphs to the
# font perturbs the hint program for *existing* glyphs, which shifts their
# subpixel rasterisation.  We freeze each unchanged glyph by overwriting its
# fresh charstring with the byte-identical program from the previously
# committed OTF (subr calls inlined so subr-index differences don't matter).

def _subr_bias(n):
    return 107 if n < 1240 else (1131 if n < 33900 else 32768)


def _inline_subrs(program, subrs, bias):
    out = []
    for token in program:
        if token == 'callsubr':
            idx = out.pop() + bias
            sub = subrs[idx]
            sub.decompile()
            inlined = _inline_subrs(sub.program, subrs, bias)
            if inlined and inlined[-1] == 'return':
                inlined = inlined[:-1]
            out.extend(inlined)
        else:
            out.append(token)
    return out


def freeze_cff(otf_path, name, ref_otf):
    """Inline ref_otf's charstrings into otf_path for any unchanged glyph,
    then desubroutinize all remaining charstrings (so the next run's reference
    is already inlined and the saved bytes match exactly)."""
    _ref_top = ref_otf['CFF '].cff.topDictIndex[0]
    _ref_cs  = _ref_top.CharStrings
    _ref_subrs = _ref_top.Private.Subrs
    _ref_bias  = _subr_bias(len(_ref_subrs))

    _new_otf = _TTFont(otf_path, recalcTimestamp=False)
    _new_otf.sfnt_names = (('English (US)', 'UniqueID', name), )
    _new_otf.xuid = "-1"

    _new_cs = _new_otf['CFF '].cff.topDictIndex[0].CharStrings
    _ref_glyphs = ref_otf.getGlyphSet()
    _new_glyphs = _new_otf.getGlyphSet()

    for _name in _ref_cs.keys():
        if _name not in _new_cs:
            continue
        # Only freeze glyphs whose outlines are unchanged.  If the path differs
        # the glyph was intentionally modified and FontForge's new hints should
        # be kept.
        _rp_ref = _RecordingPen(); _ref_glyphs[_name].draw(_rp_ref)
        _rp_new = _RecordingPen(); _new_glyphs[_name].draw(_rp_new)
        if _rp_ref.value != _rp_new.value:
            continue
        _cs = _ref_cs[_name]
        _cs.decompile()
        _inlined = _inline_subrs(_cs.program, _ref_subrs, _ref_bias)
        _new_cs[_name].program  = _inlined
        _new_cs[_name].bytecode = None

    # Desubroutinize every remaining charstring so subsequent runs' references
    # are already inlined → byte-identical re-encoding.
    _new_top = _new_otf['CFF '].cff.topDictIndex[0]
    _new_subrs = getattr(_new_top.Private, 'Subrs', [])
    _new_bias = _subr_bias(len(_new_subrs))
    for _name in _new_cs.keys():
        _cs = _new_cs[_name]
        if _cs.bytecode is not None:
            _cs.decompile()
        if _cs.program is None:
            continue
        _cs.program = _inline_subrs(_cs.program, _new_subrs, _new_bias)
        _cs.bytecode = None

    _new_otf.save(otf_path)


# ---------------------------------------------------------------------------
# Per-variant build
# ---------------------------------------------------------------------------

Path(FONT_DIR).mkdir(exist_ok=True)

for v in VARIANTS:
    name = v['name']
    print(f"=== {name} ===")

    scrub_sfd(v['sfd_in'], v['sfd_out'])

    font = fontforge.open(v['sfd_out'])
    font.sfnt_names = (('English (US)', 'UniqueID', name),)
    font.xuid = "-1"

    out_base = FONT_DIR + name
    formats  = set(v['formats'])
    subset_unicodes = v.get('subset_unicodes')

    # OTF: committed if 'otf' in formats, else a temp file (needed as the
    # source for the subset+wrap WOFF path).
    keep_otf = 'otf' in formats
    otf_path = (out_base + '.otf') if keep_otf else (GENERATED + name + '-intermediate.otf')

    # Snapshot the existing OTF (if any) before overwriting, for CFF freezing.
    ref_otf = None
    if v['freeze_cff'] and keep_otf and os.path.exists(otf_path):
        ref_otf = _TTFont(otf_path)

    font.generate(otf_path, flags=('opentype',))
    print(f"  generated {otf_path}" + ('' if keep_otf else '  (intermediate)'))

    if 'ttf' in formats:
        ttf_path = out_base + '.ttf'
        font.generate(ttf_path)
        print(f"  generated {ttf_path}")

    # Full-font WOFF: let FontForge produce it directly so the CFF stays
    # subroutinized.  Wrapping the desubroutinized post-freeze OTF instead
    # would inflate the woff by ~40% with no functional gain.
    if 'woff' in formats and subset_unicodes is None:
        woff_path = out_base + '.woff'
        font.generate(woff_path)
        print(f"  generated {woff_path}")

    font.close()

    if ref_otf is not None:
        freeze_cff(otf_path, name, ref_otf)
        print(f"  froze CFF for {otf_path}")

    # Delta WOFF: wrap the intermediate OTF and subset to just the codepoints
    # this variant overrides.  Subsetter drops unreachable glyphs, tables and
    # CFF subroutines so the output is tiny (a few hundred bytes per glyph).
    if 'woff' in formats and subset_unicodes is not None:
        woff_path = out_base + '.woff'
        wrapped = _TTFont(otf_path, recalcTimestamp=False)
        subsetter = _Subsetter()
        subsetter.populate(unicodes=subset_unicodes)
        subsetter.subset(wrapped)
        wrapped.flavor = 'woff'
        wrapped.save(woff_path)
        print(f"  generated {woff_path}  (subset to {len(subset_unicodes)} codepoints)")

    if not keep_otf:
        os.unlink(otf_path)
